language: objective-c
before_install:
    - export LANG=en_US.UTF-8
    - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
    - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
    - cd Example && pod install
script: "xctool clean test -workspace EDOpenURLCategory.xcworkspace -scheme EDOpenURLCategoryExampleApp -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO"
