language: objective-c
script: "xcodebuild -workspace Example/EDOpenURLCategory.xcworkspace -scheme EDOpenURLCategoryExampleApp ONLY_ACTIVE_ARCH=NO -destination 'platform=iOS Simulator,name=iPhone 6,OS=8.1' clean test"
